import 'package:flutter/material.dart';
import 'package:typesafe_firebase_firestore_example/firestore/models.dart';

Future<String> addUser(String name) async {
  final UserDataStore store = UserDataStore();
  final UserProfile newUser = UserProfile();
  newUser.name = name;
  newUser.uid = "userId_$name";

  // Add document with autogenerated id
  final doc = (await store.UserProfiles.add(newUser));

  final AuditTrailEntry entry = AuditTrailEntry();
  entry.uid = newUser.uid;
  entry.name = newUser.name;
  entry.modifiedAt = DateTime.now();
  entry.modifiedBy = "System";

  // Add document with specified id
  final entryDoc = await doc.AuditTrail.add(entry, "1");

  return "${doc.id} : ${entryDoc.id}";
}

class AddUserWidget extends StatefulWidget {
  const AddUserWidget({super.key});

  @override
  State<StatefulWidget> createState() => _AddUserState();
}

class _AddUserState extends State<AddUserWidget> {
  final TextEditingController _userNameController = TextEditingController();

  String _docId = "No user fetched yet";

  void _addUser() async {
    String input = _userNameController.text.trim();
    String docId;
    if (input.isEmpty) {
      docId = "Please enter a User Name";
    } else {
      // Replace this with an actual API call using the 'http' package
      docId = await addUser(input);
    }
    setState(() {
      _docId = docId;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(50.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // Input view for User ID
          TextField(
            controller: _userNameController,
            decoration: const InputDecoration(
              labelText: "Enter User Name",
              border: OutlineInputBorder(),
            ),
            keyboardType: TextInputType.number,
          ),
          const SizedBox(height: 20),

          // Button to trigger fetch
          ElevatedButton(onPressed: _addUser, child: const Text("Add User")),
          const SizedBox(height: 30),

          // Display view for User Name
          Text(
            _docId,
            style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
        ],
      ),
    );
  }
}
